site_name: Tef Docs
# site_url:
site_description: Some Internal Documention
site_author: Daniel Rodriguez
# repo_url:
copyright: Copyright &copy; 2025 Daniel Rodriguez

extra_css:
  - stylesheets/extra.css

plugins:
  - search

theme:
  name: material

  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate

markdown_extensions:
  - attr_list
  - footnotes
  - toc:
      permalink: true

  - pymdownx.blocks.admonition
  - pymdownx.blocks.html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde

nav:
  - General:
    - general/index.md
    - general/fakeclient.md
    - general/cyberresilience.md
    - general/misc.md
  - Fixed:
    - devices/o2/index.md
    - devices/o2/7741/index.md
    - devices/o2/6741/index.md
  - ONT:
    - devices/ont/index.md
    - devices/ont/ugg-vlan-faking.md
    - devices/ont/ugg-mitra.md
    - devices/ont/ugg-askey.md
  - FMS:
    - devices/fms/index.md
  - Fritz:
    - General:
      - devices/fritz/index.md
    - Fiber:
      - devices/fritz/fiber/index.md
      - devices/fritz/fiber/5530.md
    - Cable:
      - devices/fritz/cable/index.md
      - devices/fritz/cable/ntp-ipv6.md
